### ISSUE TITLE
Cant deploy to multiple Env

### ISSUE THREAD

**Issue by Baires** [karlfreeman/middleman-deploy#82]
Im under a load balancing env so I need to run several deploys at once

This is my config

```ruby
#config.ru
case ENV['TARGET'].to_s.downcase
when 'production1'
  activate :deploy do |deploy|
    deploy.method   = :rsync
    deploy.host   = 'static-prod'
    deploy.clean = true
  end
when 'production2'
  activate :deploy do |deploy|
    deploy.method   = :rsync
    deploy.host   = 'static-prod2'
    deploy.clean = true
end
when 'staging'
  activate :deploy do |deploy|
    deploy.method   = :rsync
    deploy.host   = 'static-dev'
    deploy.clean = true
  end
end
```

```ruby
#Rakefile
namespace :deploy do
  def deploy(env)
    puts "Deploying to #{env}"
    system "TARGET=#{env} bundle exec middleman deploy"
  end

  task :staging do
    deploy :staging
  end

  task :production1 do
    deploy :production1
  end

  task :production2 do
    deploy :production2
  end
end
```

When I ran `rake deploy:production1` its prints `Deploying to production1` but nothing happens. Although if I ran `TARGET=production1 bundle exec middleman deploy` its works.

Any idea?

**Comment by toobulkeh** [comment]
The pattern I use for multi-environment rake tasks is:

```
#Rakefile
task deploy: :environment do
    ...
end
```

Note that this is for Rails environments and probably needs a receptive style like your config.ru to pick up the variable, as I'm pretty sure this command compiles to: `ENV=#{:environment} rake deploy`

Hope this helps.
