### ISSUE TITLE
support for user github page

### ISSUE THREAD

**Issue by khoan** [karlfreeman/middleman-deploy#83]
Is there a way to configure git to push build to master branch? See [User, Organization, and Project Pages](https://help.github.com/articles/user-organization-and-project-pages)

**Comment by toobulkeh** [comment]
Hey @khoan. Yup, this is what we use regularly:

```
activate :deploy do |deploy|
  deploy.build_before = true
  deploy.method = :git
  deploy.branch = "master"
end
```

Hope this helps!

**Comment by khoan** [comment]
perfect! thanks.

I've added commit sha to make it easier to track which commit were deployed, instead of the default message.

```ruby
activate :deploy do |deploy|
  # ...
  deploy.commit_message = 'Site updated to ' << `git log --pretty="%h" -n1`
```
